### ISSUE TITLE
webpack-reactjs example not working

### ISSUE THREAD

**Issue by fakob** [justadudewhohacks/opencv-electron#12]
Hi,
When running the webpack-reactjs example only the source image is shown, but no controls nor the result image. 
The console throws a `compiled with warnings`:
```
WARNING in ./node_modules/opencv4nodejs/lib/cv.js
15:7-68 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js
 @ ./app/Root.jsx
 @ ./app/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./app/index.jsx

WARNING in ./node_modules/opencv4nodejs/lib/cv.js
17:7-70 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js
 @ ./app/Root.jsx
 @ ./app/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./app/index.jsx
```

And before that, the first log message from electron says:
```
Electron Security Warning This renderer process has Node.js integration enabled and attempted to load remote content. This exposes users of this app to severe security risks.
For more information and help, consult https://electronjs.org/docs/tutorial/security
```

Not sure if these warnings are related though. 

Initially I wanted to move the opencv4nodejs code in my own [MoviePrint project](https://github.com/fakob/MoviePrint_v004) from the main thread to a renderer window(thread), but this renderer window always crashes after a random amount (usually around 3-5 depending on the video size) of `readAsync` calls. Without any error message. After having spend much time trying to debug it I thought to try your example again. I thought that maybe there was a change in opencv4nodejs or the electron version which causes it as I also got the same warnings there. This is how I then ran into this issue here.

If my initial problem is related to this issue, I have no clue. Any ideas?

I am running the following:
_opencv-build: 0.0.12
opencv4nodejs: 4.2.1
electron: 1.8.4
node: v9.8.0
npm : 5.6.0_

**Comment by aramic** [comment]
+1

When I run `npm start`, I get the following message:
```
> @opencv-electron/webpack-reactjs@0.0.0 start /Users/USERNAME/Code/opencv-electron/webpack-reactjs
> electron ./main/main.js

failed to load react dev tools process.env.REACT_DEVTOOLS_PATH: undefined
failed to load redux dev tools process.env.REDUX_DEVTOOLS_PATH: undefined

```

**Comment by justadudewhohacks** [comment]
The reason why this example only shows an image, because the controls from the other example are not implemented in the webpack-reactjs examples. I was to lazy to port the full example to react.

Also loading react and redux devtools is optional, you can simply ignore that message.

Regarding the crashing of cap.read: I am pretty sure this is because of the same issue I faced with `mat.getData` quite some time ago, more precisely with returning node buffers in an electron application. For some odd reason I could fix it by providing a `freeBufferCallback` to the `Nan::NewBuffer`  call in the binding for `getData`: `Nan::NewBuffer(data,` size, freeBufferCallback, 0)`. I forgot to implement that for the other bindings, that return node buffers (VideoCapture.read and cv.imdecode).

**Comment by fakob** [comment]
Thanks for the clarification regarding the webpack example, so my assumption was wrong. But great that you might know how to fix the original issue. 
Just to clarify. If I recall correctly did the `VideoCapture.readAsync` function work fine for me when running it from the main thread. The crashing only started when I moved the `readAsync` function to a renderer.

**Comment by justadudewhohacks** [comment]
Yes exactly. The buffer issue should only appear in the renderer thread. But reading the frames from remote/ main thread  is pretty slow because buffers are serialized.

**Comment by justadudewhohacks** [comment]
Please consider my last comment in #13

**Comment by wbern** [comment]
@justadudewhohacks I'm starting to wonder if the transport layer you mention (cv data transferring from main process to renderer process?) is what's causing these random issues. Is serialization and deserialization causing the issues described both here and in #13?

>If I recall correctly did the VideoCapture.readAsync function work fine for me when running it from the main thread. The crashing only started when I moved the readAsync function to a renderer.

This is identical to my statement. Renderer process is where all the problems come up.

Edit: See https://github.com/justadudewhohacks/opencv-electron/issues/13#issuecomment-396700320, should be the fix for imencode at least. Not sure about readAsync in this issue.

**Comment by justadudewhohacks** [comment]
If `imencode` is not the cause of the crashes in this issue, then please consider my comment [here](https://github.com/justadudewhohacks/opencv-electron/issues/13#issuecomment-396515247).

**Comment by fakob** [comment]
Sorry, I had too little time to test it properly, but these are my observations so far:
* `imencode` caused the renderer thread to crash every time
* However after commenting it out and really only reading frames (synchronously) I did still have random crashes. 
This I only tested with `read` and not with `readAsync` so the solution with using `setTimeout` was not applicable for me I presume.

I will try to do some more testing in the next days. 
Btw, thank you. I very much appreciate that you have looked into it!

**Comment by fakob** [comment]
v4.5.2 seems to have fixed my original issue. thanks so much!

Regarding the issue topic as a summary I just quote from the thread.
> The reason why this example only shows an image, because the controls from the other example are not implemented in the webpack-reactjs examples. I was to lazy to port the full example to react.
